"""initial schema

Revision ID: 3bdd645ae4da
Revises: 
Create Date: 2026-05-30 13:02:12.319559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bdd645ae4da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTRATION', 'LOGIN', 'PASSWORD_RESET', name='otppurpose'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('sms_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'PENDING', name='smsstatus'), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'PROVIDER', 'DRIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_photo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BOOKING_UPDATE', 'PAYMENT', 'AUCTION', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('response_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('cargo_type', sa.Enum('AGRICULTURE', 'FOOD', 'CONSTRUCTION', 'RETAIL', 'INDUSTRIAL', 'OTHER', name='cargotype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_tons', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('volume_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('pickup_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('pickup_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('destination_address', sa.Text(), nullable=True),
    sa.Column('destination_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('destination_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Enum('STANDARD', 'EXPRESS', 'URGENT', name='urgencylevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUOTED', 'BOOKED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('requires_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('preferred_departure_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auctions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='auctionstatus'), nullable=False),
    sa.Column('winning_bid_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['winning_bid_id'], ['auction_bids.id'], name='fk_auctions_winning_bid', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('MOTORCYCLE', 'VAN', 'PICKUP', 'TRUCK', 'REFRIGERATED_TRUCK', 'CONTAINER', name='vehicletype'), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('capacity_tons', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('capacity_volume_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_location_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('current_location_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('auction_bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auction_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_winning', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('base_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('insurance_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('tracking_code', sa.String(length=20), nullable=False),
    sa.Column('pickup_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_tracking_code'), 'bookings', ['tracking_code'], unique=True)
    op.create_table('shared_cargo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('route_from', sa.Text(), nullable=False),
    sa.Column('route_from_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('route_from_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('route_to', sa.Text(), nullable=False),
    sa.Column('route_to_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('route_to_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('total_capacity_tons', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('used_capacity_tons', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('price_per_ton', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULL', 'DEPARTED', 'CANCELLED', name='sharedcargostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_cargo_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shared_cargo_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tons_booked', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cargo_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='sharedcargobookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_cargo_id'], ['shared_cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('shared_cargo_booking_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.Enum('MPESA', 'AIRTEL_MONEY', 'TIGO_PESA', 'HALOPESA', 'BANK', name='paymentmethod'), nullable=False),
    sa.Column('provider_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_cargo_booking_id'], ['shared_cargo_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('shared_cargo_bookings')
    op.drop_table('shared_cargo')
    op.drop_index(op.f('ix_bookings_tracking_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('auction_bids')
    op.drop_table('vehicles')
    op.drop_table('drivers')
    op.drop_table('auctions')
    op.drop_table('shipments')
    op.drop_table('providers')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('sms_logs')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
